#ifndef FXN_MIDDLEWARE_ERRORCODE_H
#define FXN_MIDDLEWARE_ERRORCODE_H

enum class ErrorCode {
    NO_ERROR = 0,
    NO_CONNECTION = 100,
    INVALID_INPUT_JSON = 101,
    INVALID_INPUT_VALUE = 102,
    UNKNOWN
};

#endif //FXN_MIDDLEWARE_ERRORCODE_H
