#ifndef FXN_MIDDLEWARE_RESULTTYPE_H
#define FXN_MIDDLEWARE_RESULTTYPE_H

enum class ResultType {
    OK, // 0
    ERROR = 100,
    ERROR_BUSY,
    ERROR_INVALID_JSON_FORMAT,
    ERROR_INVALID_INPUT,
    ERROR_OUT_OF_RANGE,
    UKnown
};

#endif //FXN_MIDDLEWARE_RESULTTYPE_H
